---
title: "Frequentist and Bayesian Meta-Analysis: Implementation in R"
author: 
  - name: Dejene Chala
    affiliation: Department of Statistics
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: cosmo
    highlight: tango

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)

# Load required libraries (must be installed beforehand)
library(bayesmeta)
library(meta)
library(metafor)
```



```{r}
# Load BCG vaccine dataset from metafor
data(dat.bcg)

# Compute log odds ratios and sampling variances
BCGdat <- escalc(
  measure = "OR",
  ai = tpos, bi = tneg,
  ci = cpos, di = cneg,
  data = dat.bcg,
  slab = paste(author, year, sep = ", ")
)

# Display first few rows
head(BCGdat)
```



```{r}
# DerSimonian-Laird random-effects model
res_fe <- rma(yi, vi, data = BCGdat, method = "DL")

summary(res_fe)
```

```{r}
# 3. Frequentist Meta-Analysis
#
# The following lines of  code were used to fit the frequentists
# Meta analysis to the data.
############################


# meta package (REML + HK)
frm <- metagen(
  TE = yi,
  seTE = sqrt(vi),
  studlab = paste(author, year, sep = ", "),
  data = BCGdat,
  sm = "OR",
  method.tau = "REML",
  method.random.ci = "HK",
  title = "BCG Vaccine Data"
)

summary(frm)
```

```{r}
# metafor package (DL)
rma_dl <- rma(yi, vi, method = "DL", data = BCGdat)
print(rma_dl)

```

```{r}

############################
# 4. Forest & Radial Plots

# Note that forest plot is  a powerful graphical procedure in MA
# used to display your MA results graphically with all numerical details 
# Included.'
# this days beside its dependence on single threshold p-value
# it remains to the most prominent method of reporting results in MA
############################


# Reduce overall font size
par(cex = 0.7)   # global scaling (try 0.6 if you want smaller)

forest(frm,
       header = TRUE,
       layout = "RevMan",
       col.square = "blue",
       col.diamond.random = "red",
       col.diamond.fixed = "green",
       
       # Control font size
       cex = 0.7,          # study labels
       fontsize = 7,       # text columns
       
       # Force 2 decimal places everywhere
       digits = 2,
       digits.stat = 2,
       digits.se = 2,
       digits.pval = 2,
       digits.tau2 = 2,
       digits.I2 = 2,
       digits.Q = 2
)

```
```{r}
par(cex = 0.7)

radial(rma_dl,
       digits = 2,
       cex = 0.7)
```

```{r}
############################
# 5. Heterogeneity & Influence

# THIS IS THE MOST IMPORTANT META ANALYSIS STEP THAT MOST STUDIES IGNORE
# WE MUST TRUST OUR DATA WITH CAUTION.
# the end results of analysis might be affected by outliers, influentials
# or just extreme cases. 
# most of current meta analysis procedures ignores this steps even if
# its extremely important
############################

baujat(frm)

inf <- influence(rma_dl)
plot(inf)
plot(inf, layout = c(4,1))

```

```{r}

############################
# 6. Funnel Plots
#
# --- One of the most important issue to consider in MA is to check
# the presence of publication bias.
# the most common graphical method to check the presence of 
# Publication bias is thorugh examining the funnel plot
# 
# even if the procedure is quite subjective to the reader,
# Funnel plot remains to be most popular graphical procedure in MA
# to check for the presence of publication bias in the underlying 
# Meta analysis results.

############################

par(mfrow = c(2,2))
funnel(rma_dl, main = "Standard Error")
funnel(rma_dl, yaxis = "vi", main = "Sampling Variance")
funnel(rma_dl, yaxis = "seinv", main = "Inverse SE")
funnel(rma_dl, yaxis = "vinv", main = "Inverse Variance")

par(mfrow = c(1,1))
funnel(rma_dl,
       level = c(90,95,99),
       shade = c("yellow","orange","pink"),
       refline = 0,
       legend = TRUE)


```
```{r}
#library(metafor)

metabias(frm, method.bias = "linreg")

taf <- trimfill(frm)
print(taf)
funnel(taf)

```



```{r}
############################
# 8. GOSH Plot
# This a powerfull statistical procedure used to test the presence of 
# Heterogeneity in our data.
# 
# it is graphical method aims at identifying the number of homogenous 
# subgroups in the data.
############################

sav <- gosh(rma_dl)
plot(sav, out = 13, breaks = 100)
```

```{r}

############################
# 9. Subgroup Analysis
############################

frms <- metagen(
  TE = yi,
  seTE = sqrt(vi),
  subgroup = alloc,
  studlab = author,
  data = BCGdat,
  sm = "OR",
  method.tau = "REML",
  method.random.ci = "HK"
)

forest(frms,
        header = TRUE,
       layout = "RevMan",
       col.square = "blue",
       col.diamond.random = "red",
       col.diamond.fixed = "green",
       # Control font size
       cex = 0.7,          # study labels
       fontsize = 7,       # text columns
       
       # Force 2 decimal places everywhere
       digits = 2,
       digits.stat = 2,
       digits.se = 2,
       digits.pval = 2,
       digits.tau2 = 2,
       digits.I2 = 2,
       digits.Q = 2)


```

```{r}

# Meta-regression for subgroup differences
srem_mod <- rma(yi, vi, mods = ~ alloc, data = BCGdat)
summary(srem_mod)
regtest(srem_mod)


```

```{r}
############################
# 10. Bayesian Meta-Analysis
############################

# Vague prior
ma01 <- bayesmeta(
  y = BCGdat[, "yi"],
  sigma = sqrt(BCGdat[, "vi"]),
  mu.prior.mean = 0,
  mu.prior.sd = 25,
  tau.prior = function(t) dhalfnormal(t, scale = 0.5)
)

print(ma01$summary, digits = 4)

forestplot(ma01, addfit = TRUE, showweights = TRUE)

funnel(ma01,
       level = c(90,95,99),
       shade = c("white","gray55","gray75"),
       refline = 0,
       legend = TRUE)


```



```{r}
############################
# 11. Prior Sensitivity
############################

# Jeffreys prior
ma011 <- bayesmeta(BCGdat, tau.prior = "Jeffreys")
print(ma011$summary, digits = 4)

# Half-Cauchy prior
ma012 <- bayesmeta(
  y = BCGdat[, "yi"],
  sigma = sqrt(BCGdat[, "vi"]),
  mu.prior = c(mean = 0, sd = 25),
  tau.prior = function(x) dhalfcauchy(x, scale = 10)
)

print(ma012$summary, digits = 4)

############################
# 12. Informative Prior
############################

ma013<-bayesmeta(y = BCGdat[, "yi"],
  sigma = sqrt(BCGdat[, "vi"]),
  mu.prior = c(mean = 0, sd = 4),
  tau.prior = function(x) dhalfcauchy(x, scale = 0.5))
print(ma013$summary, digits = 4)

tp <- TurnerEtAlPrior(
  outcome = "surgical",
  comparator1 = "pharmacological",
  comparator2 = "placebo / control"
)

ma014 <- bayesmeta(
  BCGdat,
  mu.prior.mean = 0,
  mu.prior.sd = 4,
  tau.prior = tp$dprior
)

print(ma014$summary, digits = 4)


```

```{r}
forest(ma014, addfit = TRUE, showweights = TRUE)
forest(ma014,addpred=TRUE,addfit=TRUE,showweights=T,
       xlim=c(-5,5), at=seq(-1,1,by=1), shade="zebra",
       cex=0.9, header="Study Authors",col="blue",colshade="lightgrey")




funnel(ma014,
       level = c(90,95,99),
       shade = c("white","gray55","gray75"),
       refline = 0,
       legend = TRUE)
```



```{r}
############################
# 13. Posterior Inference
############################

ma014$post.interval(tau.level = 0.95)
ma014$post.interval(mu.level = 0.95)

plot(ma014, main = "Posterior Distribution")

ma014$rposterior(n = 10)


```

```{r}

############################
# 14. Shrinkage Estimates
############################

she <- ma014$theta[,1:4]
print(she, digits = 4)

############################
# 15. Posterior Density Plot
############################

x <- seq(-3.5, 0.5, length = 200)

plot(x, ma012$dposterior(mu = x),
     type = "n",
     xlab = "Effect",
     ylab = "Density")

abline(h = 0, v = 0, col = "gray")

lines(x, ma012$dposterior(mu = x), col = "red")
lines(x, ma012$dposterior(mu = x, predict = TRUE), col = "blue")

############################################################
# End of Script
############################################################
```

